"""GitHub operations: feature branches, commits, and pull requests.

Uses the GitHub REST API via a personal access token. The token must have
`repo` scope to create branches, commit files, and open PRs.
"""
from __future__ import annotations

import base64
import logging
from typing import List, Optional

import requests

from config import settings

logger = logging.getLogger(__name__)


class GitOps:
    """GitHub API operations for the spec-driven-framework."""

    def __init__(self, token: Optional[str] = None, repo: Optional[str] = None):
        self.token = token or settings.GITHUB_API_KEY
        self.repo = repo or settings.GITHUB_REPO
        if not self.token:
            raise ValueError("GITHUB_API_KEY is not set.")
        if not self.repo:
            raise ValueError("GITHUB_REPO is not set (e.g. 'frankbelk/spec-driven-framework').")

    def _headers(self) -> dict:
        return {
            "Authorization": f"token {self.token}",
            "Accept": "application/vnd.github+json",
        }

    def _api(self, path: str, method: str = "GET", **kwargs) -> dict:
        url = f"https://api.github.com/repos/{self.repo}{path}"
        resp = requests.request(method, url, headers=self._headers(), **kwargs)
        if resp.status_code >= 400:
            raise Exception(f"GitHub API error ({resp.status_code}): {resp.text}")
        return resp.json() if resp.content else {}

    def create_feature_branch(self, ticket_id: str) -> str:
        """Create (or reuse) a feature branch for a Linear ticket."""
        branch = f"feat/{ticket_id.lower()}"
        # Get the default branch SHA.
        repo = self._api("")
        default_branch = repo.get("default_branch", "main")
        ref = self._api(f"/git/ref/heads/{default_branch}")
        sha = ref["object"]["sha"]
        # Try to create the branch; ignore if it already exists.
        try:
            self._api("/git/refs", method="POST", json={
                "ref": f"refs/heads/{branch}",
                "sha": sha,
            })
            logger.info("Created branch %s", branch)
        except Exception:
            logger.info("Branch %s already exists", branch)
        return branch

    def commit_artifacts(self, branch: str, artifact_names: List[str]) -> None:
        """Commit artifact files to the given branch via the GitHub API."""
        for name in artifact_names:
            path = f"sdd/{name}"
            try:
                with open(name, "rb") as f:
                    content = base64.b64encode(f.read()).decode()
            except FileNotFoundError:
                logger.warning("Artifact %s not found locally, skipping", name)
                continue
            try:
                self._api(f"/contents/{path}", method="PUT", json={
                    "message": f"Add {name}",
                    "content": content,
                    "branch": branch,
                })
                logger.info("Committed %s to %s", path, branch)
            except Exception as e:
                logger.warning("Failed to commit %s: %s", path, e)

    def create_pull_request(self, branch: str, ticket_id: str, title: str) -> str:
        """Open a PR from the feature branch to the default branch."""
        repo = self._get("")
        default_branch = repo.get("default_branch", "main")
        pr = self._api("/pulls", method="POST", json={
            "title": f"[{ticket_id}] {title}",
            "head": branch,
            "base": default_branch,
            "body": f"Automated PR for {ticket_id} generated by spec-driven-framework.",
        })
        return pr.get("html_url", "")

    def _get(self, path: str) -> dict:
        return self._api(path, method="GET")